# This is a basic workflow to help you get started with Actions

name: Generate Lighthouse Report

# Controls when the workflow will run
on:
  workflow_call:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  generateReport:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      RT_URL: ${{ secrets.RT_URL }}
      RT_USER_NAME: ${{ secrets.RT_USER_NAME }}
      RT_USER_PASS: ${{ secrets.RT_USER_PASS }}


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Setup project
        run: npm install --silent
     
      - name: Echo secrets to .env
        run: |
          echo $RT_URL > .env
          echo $RT_USER_NAME >> .env
          echo $RT_USER_PASS >> .env


      # Runs a set of commands using the runners shell
      - name: Run script
        run: HTML_MODE=browser node index.js
        
      - uses: actions/upload-artifact@v3
        with:
          name: report-properties
          path: report.properties
    
      - name: Create report archive
        run: zip -r report.zip index.html reports/
   
      - uses: actions/upload-artifact@v3
        with:
          name: report-artifact
          path: report.zip
