# This is a basic workflow to help you get started with Actions

name: Generate Lighthouse Report and Notify Devs

# Controls when the workflow will run
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Run the schedule around 9:45 AM IST. Some times the schedule is delayed by 10-15mins
    # Avg run time is 17 minutes. So before 10:30AM there should be an output
    - cron:  '15 4 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  generateReport:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/generate_report
  notifyDev:
    needs: generateReport
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/notify_dev
