# This is a basic workflow to help you get started with Actions

name: Notfiy Devs

# Controls when the workflow will run
on:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  notifyDev:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Setup project
        run: npm install --silent
        
      - uses: actions/download-artifact@v3
        with:
          name: report-properties
      - name: Load properties file into environment
          run: cp report.properties .env

      # Runs a set of commands using the runners shell
      - name: Run script
        run: node notify.js
